server:
  port: 80
  context-path: /sbe
spring:
  session:
     store-type: none
  thymeleaf:
      prefix: classpath:/templates/
  ##mvc:
    #static-path-pattern: /**
  #web:
    #upload-path: E:/test/
  #resources:
    #static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://172.16.47.142:3306/seckill?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
    username: root
    password: mysql
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  # REDIS (RedisProperties)
  # Redis数据库索引（默认为0）
  redis:
    database: 0
    # Redis服务器地址
    host: 172.16.47.142
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    #password: root

    #可添加从redis服务器来提高吞吐量
    #cluster:
      #nodes: 192.168.211.134:7000,192.168.211.134:7001,192.168.211.134:7002
      #maxRedirects: 6
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接超时时间（毫秒）
    timeout: 5000
mybatis:
  mapperLocations: classpath:mybatis-mapper/*.xml
  typeAliasesPackage: me.importtao.seckillbackend.model
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#配置日志
#logging.config: classpath:logback-config.xml
#token超时时间（ms）
tokenExpire: 1800000
file:
  imgPath: E:/test/
  filePath: E:/test/

